# Generated by Django 5.0.6 on 2024-06-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list',
            name='id',
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='task',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
