# Generated by Django 5.0.6 on 2024-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_list_id_alter_todo_list_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='id',
            field=models.IntegerField(default=612, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
