# Generated by Django 5.0.6 on 2024-06-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_list_id_alter_todo_list_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
