# Generated by Django 5.0.6 on 2024-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_todo_list_todo_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='todo_lists',
        ),
    ]
